### PR TITLE
Added key event, fixed bugs, improved readability of code

### PR DESCRIPTION
**Pull request by Steveb175**
1.  Added key event "Enter" feature to search bar
2. Modified click event for searchBtn to be more concise.
3. Slightly changed the location of the weather icon through JS manipulation so it doesn't go behind the header.
4. Added a h1 within the header to improve SEO.
5. Added pints to either side of the header.
6. Added margin above the temperature so that it doesn't cross over the header.

I think that's everything...?

### CODE REVIEW

**Review by Amartinez2075 — CHANGES_REQUESTED** [review]
So on line 33 of your javascript code the margin should be at least m-6 or larger so that it doesn't touch the weather symbol, m-6 is fine for cloudy weather but will need to be larger for sunny weather symbol. And the weather symbol itself needs to be static so that way it doesn't move down when you scroll on the page.  It will still touch the columns if its a sun symbol tho.

**Comment by Steveb175** [comment]
> So on line 33 of your javascript code the margin should be at least m-6 or larger so that it doesn't touch the weather symbol, m-6 is fine for cloudy weather but will need to be larger for sunny weather symbol. And the weather symbol itself needs to be static so that way it doesn't move down when you scroll on the page. It will still touch the columns if its a sun symbol tho.

I think the goal that @githubkyle had when he made it in the background was so that it would be visible at all times when scrolling. That's why we had discussed yesterday about closing the margins a bit on the cards so that we could allow the weather symbol to be visible at all times.

**Comment by Steveb175** [comment]
I went ahead and moved the weather icon to the right side. Also added a main for SEO and added another closing div that was missing (probably due to prettier messing with HTML on a previous commit).

**Review by Amartinez2075 — APPROVED** [review]
Its good

**Pull request merged**
